### ISSUE TITLE
Unable to start the Python language server

### ISSUE THREAD

**Issue by mzannoni** [lgeiger/ide-python#34]
Of course, pyls is correctly installed, Python and Python3 are present in /usr/bin.
From inside Python, I can import pyls without issue.
Until yesterday it was ok.

**Comment by lgeiger** [comment]
We just released `v0.2.3` with a fix for properly recognizing `pyls`.
Could you try again with `v0.2.3`?

**Comment by mzannoni** [comment]
Nope... still the same.
I attach here a screenshot of the error in Atom.
![python_ide_err](https://user-images.githubusercontent.com/29273478/32142086-7b2f58bc-bc90-11e7-8607-631c93ca3593.png)

Since it's started occurring it's always the same, and of course the Python IDE in Atom does not appear to work.

Let me know if you need more details about my system.

Other question... is there a way to install the latest version that was working correctly? I'd really need it...

**Comment by mzannoni** [comment]
If it can be of any help, output from Python interpreter:
`Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyls
>>> pyls.__version__
'0.8.0'
>>>`

**Comment by mzannoni** [comment]
Ok, found an issue, I guess it's probably only in my case... Somehow the pyls bin was not in the PATH. Now it seems to work, after I've added it to the PATH in bash profile.
I think it was my mistake, I guess we can close this.

**Comment by lgeiger** [comment]
Glad it's working now. If you don't want to add pyls to your path in the bashrc, you can also configure the absolut path to pyls in the ide-python settings.

**Comment by mzannoni** [comment]
Thanks a lot.
Still wondering what changed that broke it at a certain point...
However, now it's ok.


On Oct 29, 2017 11:17, "Lukas Geiger" <notifications@github.com> wrote:

Glad it's working now. If you don't want to add pyls to your path in the
bashrc, you can also configure the absolut path to pyls in the ide-python
settings.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lgeiger/ide-python/issues/34#issuecomment-340251325>,
or mute the thread

**Comment by DreamAccess** [comment]
Hello everyone,

I am getting the same error, please can you tell me how you fixed your issue ? 

Thank you.

**Comment by danielrocker** [comment]
in terminal:
atom --safe (do not load packages)

in atom:
> file > quit

then start Atom again by the icon

Sorry about English

**Comment by mzannoni** [comment]
In general, I could fix this issue in basically all of my machines (real, virtual, Fedora, Ubuntu, ...) with the following two commands in the terminal:
`pip3 install --user --upgrade python-language-server[all]`
`pip install --user --upgrade python-language-server[all]`

I don't know why, but upgrading pyls and its dependencies for both Python3 and Python2 fixes the issue for me in most cases.

It may be also useful, before the two commands above, to upgrade pip itself:
`pip3 install --user --upgrade pip`

**Comment by DavidMStraub** [comment]
In my case the problem was that `pyls` was only installed for Python 3, but the Python executable in the `ide-python` settings was set to the default value `python` (calling Python 2 on Ubuntu). Setting this to `python3` solved the problem for me.

**Comment by shred86** [comment]
Thanks @DavidMStraub, setting the 'Python Executable' to `python3` under Settings for ice-python fixed it for me.

**Comment by dstanner** [comment]
I was having this problem and none of the above solutions were working for me. `pyls` was working find when I'd start from the command line, but not when I'd start from the app icon.

But then I realized I had pip installed while in an anaconda virtualenv. I exited the virtualenv to my base environment, then pip installed again, and now it seems to be working fine.

So, if you're having this problem and installed from within the virtualenv, try re-installing in the base env.

**Comment by devops0218** [comment]
What worked for me is to open Atom from the location where Atom.exe file is situated.
After opening Atom, open a terminal session and type
python -m pip install python-language-server[all]
it works like magic.

**Comment by Digion** [comment]
Official installation instructions:
If you get an error similar to 'install_requires' must be a string or list of strings then please upgrade setuptools before trying again.
pip install -U setuptools
pip3 install -U setuptools

pip install 'python-language-server[all]'
pip3 install 'python-language-server[all]'

You can verify that everything is correctly installed by running 
python -m pyls --help 
from the command line.

**Comment by Turbotanten** [comment]
> In my case the problem was that `pyls` was only installed for Python 3, but the Python executable in the `ide-python` settings was set to the default value `python` (calling Python 2 on Ubuntu). Setting this to `python3` solved the problem for me.

How do I find the settings for `ide-python`?

**Comment by paulathomas** [comment]
I am having the same problem but in a slightly different flavour:

when I try to install pyls via pip3 I get version 0.1.6 so I try to install 0.8 and get the following message:
ERROR: Could not find a version that satisfies the requirement pyls==0.8 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6)
ERROR: No matching distribution found for pyls==0.8
Help!!

**Comment by lavander99x** [comment]
> Ok, found an issue, I guess it's probably only in my case... Somehow the pyls bin was not in the PATH. Now it seems to work, after I've added it to the PATH in bash profile.
> I think it was my mistake, I guess we can close this.

it also happy to me too, could you help me out ? i have been tried many ways so far but cant fix it, cant write python code on atom

**Comment by chrisx06** [comment]
![image](https://user-images.githubusercontent.com/67241654/132982649-687608a9-a577-42ac-b900-2cbfc7433edf.png)
Why is it giving this error
